---

- name: cleanup solr role leftovers
  shell: "rm -fr /root/solr*"
  ignore_errors: yes

- name: add hosts entry
  lineinfile: dest=/etc/hosts line='127.0.0.1 {{ item.key }}' owner=root group=root mode=0644
  with_dict: "{{ typo3.cms.sites }}"
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  ignore_errors: yes

- name: get solr extension for TYPO3 7.x
  become: true
  become_user: vagrant
  composer: command=require arguments="apache-solr-for-typo3/solr:6.5.0" working_dir={{ typo3_webroot }}{{ item.key }} php_path="/usr/bin/php7.0"
  when: item.key | match('^((7)\\.(\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: get solr extension for TYPO3 8.x
  become: true
  become_user: vagrant
  composer: command=require arguments="apache-solr-for-typo3/solr:7.5.0" working_dir={{ typo3_webroot }}{{ item.key }} php_path="/usr/bin/php7.0"
  when: item.key | match('^((8)\\.(\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: get solr extension for TYPO3 9.x
  become: true
  become_user: vagrant
  composer: command=require arguments="apache-solr-for-typo3/solr:dev-master" working_dir={{ typo3_webroot }}{{ item.key }} php_path="/usr/bin/php7.2"
  when: item.key | match('^((9)\\.(\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes


- name: typo3_console install extension solr for 6.x and 7.x
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms extension:install solr"
  become: true
  become_user: vagrant
  when: item.key | match('^((7)\\.(\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

##
# EXT:solr for TYPO3 7 & 8 & dev-master
##
- name: install solr core configuration from extension for TYPO3 7.6
  shell: "mkdir -p /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/data/data"
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: copy configuration
  shell: "cp -R {{ typo3_webroot }}{{ item.key }}/typo3conf/ext/solr/Resources/Private/Solr/* /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/data"
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: fix permissions
  shell: "chown solr:solr -R /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}"
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

###
# Dist and Contrib folder
##

- name: Copy tx_solr setup dump
  become: true
  become_user: vagrant
  copy: src=configure_tx_solr_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}.sql dest=/tmp force=yes
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"

- name: Import tx_solr setup dump
  become: true
  become_user: vagrant
  shell: "mysql -utypo3 -psupersecret {{ item.key | regex_replace('\\.', '_') }} < /tmp/configure_tx_solr_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}.sql"
  when: item.key | match('^((7|8|9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: Update solr connections for TYPO3 7.x and 8.x
  shell: "php {{ typo3_webroot }}{{ item.key }}/typo3/cli_dispatch.phpsh extbase solr:updateConnections"
  when: item.key | match('^((7|8)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: Update solr connections for TYPO3 9.x
  shell: "{{ typo3_webroot }}{{ item.key }}/typo3cms solr:updateconnections"
  when: item.key | match('^((9)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

##
# Install php-cs-fixer
##
- name: Install php-cs-fixer as global composer binary
  become: true
  become_user: vagrant
  command: composer global require friendsofphp/php-cs-fixer:v2.9.0

##
# Add composer bin path to PATH variable
##
- name: add /home/vagrant/.config/composer/vendor/bin/php-cs-fixer to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/home/vagrant/.config/composer/vendor/bin).*?)(["]*)$'
    line="PATH=\1\2:/home/vagrant/.config/composer/vendor/bin\3"

- name: set composer timeout
  lineinfile: >
    dest=/etc/environment
    state=present
    line="COMPOSER_PROCESS_TIMEOUT=900"