---

- name: cleanup solr role leftovers
  shell: "rm -fr /root/solr*"
  ignore_errors: yes

- name: add hosts entry
  lineinfile: dest=/etc/hosts line='127.0.0.1 {{ item.key }}' owner=root group=root mode=0644
  with_dict: "{{ typo3.cms.sites }}"
  when: item.key | match('^((6|7|8)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  ignore_errors: yes

- name: get pagebrowser extension for TYPO3 6.x
  become: true
  become_user: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }}/typo3conf/ext && mkdir pagebrowse && cd pagebrowse && wget http://typo3.org/extensions/repository/download/pagebrowse/1.3.4/zip/ -O  pagebrowse.zip && unzip pagebrowse.zip"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: typo3_console install extension pagebrowser for 6.x
  become: true
  become_user: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms extension:install pagebrowse"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: get solr extension for TYPO3 6.x
  become: true
  become_user: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }}/typo3conf/ext && wget https://github.com/TYPO3-Solr/ext-solr/archive/3.0.2.tar.gz && tar xvfz 3.0.2.tar.gz && mv ext-solr-3.0.2 solr"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: get solr extension for TYPO3 7.x and 8
  become: true
  become_user: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && composer require apache-solr-for-typo3/solr:6.1.0"
  when: item.key | match('^((7|8)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: get solr extension for TYPO3 9.x
  become: true
  become_user: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && composer require apache-solr-for-typo3/solr:dev-master"
  when: item.key | match('^((9)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes


- name: typo3_console install extension solr for 6.x and 7.x
  sudo: vagrant
  shell: "cd {{ typo3_webroot }}{{ item.key }} && ./typo3cms extension:install solr"
  when: item.key | match('^((6|7|8)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes


##
# EXT:solr for TYPO3 7 & 8 & dev-master
##
- name: install solr core configuration from extension for TYPO3 7.6
  shell: "mkdir -p /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/data/data"
  when: item.key | match('^((7|8)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: copy configuration
  shell: "cp -R {{ typo3_webroot }}{{ item.key }}/typo3conf/ext/solr/Resources/Private/Solr/* /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/data"
  when: item.key | match('^((7|8)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: fix permissions
  shell: "chown solr:solr -R /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}"
  when: item.key | match('^((7|8)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

##
# EXT:solr for TYPO3 6
##
- name: install solr core configuration from extension for TYPO3 6.x
  shell: "rm -fR /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/* && cp -R {{ typo3_webroot }}{{ item.key }}/typo3conf/ext/solr/Resources/Solr/* /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/ & chown solr:solr -R /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: install solr plugins for TYPO3 6.x
  shell: "mkdir -p /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/typo3lib"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: install access plugin for TYPO3 6.x
  shell: "wget http://www.typo3-solr.com/fileadmin/files/solr/Solr4x/solr-typo3-access-2.0.jar -O  /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/typo3lib/solr-typo3-access-2.0.jar"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: install install utils plugin for TYPO3 6.x
  shell: "wget http://www.typo3-solr.com/fileadmin/files/solr/Solr4x/solr-typo3-utils-1.1.jar -O  /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/typo3lib/solr-typo3-utils-1.1.jar"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: install language plugin for TYPO3 6.x
  shell: "wget http://www.typo3-solr.com/fileadmin/files/solr/Solr4x/commons-lang3-3.1.jar -O  /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/typo3lib/commons-lang3-3.1.jar"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: mv dist and contrib to core folder
  shell: "mv /opt/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/contrib /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/ && mv /opt/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/dist /var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: Copy solr.xml file
  copy: src=solr.xml dest=/var/solr_typo3_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}/ force=yes
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"

###
# Dist and Contrib folder
##

- name: Copy tx_solr setup dump
  become: true
  become_user: vagrant
  copy: src=configure_tx_solr_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}.sql dest=/tmp force=yes
  when: item.key | match('^((6|7|8)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"

- name: Import tx_solr setup dump
  become: true
  become_user: vagrant
  shell: "mysql -utypo3 -psupersecret {{ item.key | regex_replace('\\.', '_') }} < /tmp/configure_tx_solr_{{ item.key | regex_replace('\\.local\\.typo3\\.org','') }}.sql"
  when: item.key | match('^((6|7|8)\\.(\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: Update solr connections for TYPO3 6.x
  shell: "php {{ typo3_webroot }}{{ item.key }}/typo3/cli_dispatch.phpsh solr updateConnections"
  when: item.key | match('^((6)\\.(2|3|4|5|6|7|8|9|1\d))\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

- name: Update solr connections for TYPO3 7.x and 8.x
  shell: "php {{ typo3_webroot }}{{ item.key }}/typo3/cli_dispatch.phpsh extbase solr:updateConnections"
  when: item.key | match('^((7|8)\\.(2|3|4|5|6|7|8|9|1\d)|dev-master|master|review)\\.')
  with_dict: "{{ typo3.cms.sites }}"
  ignore_errors: yes

##
# Install php-cs-fixer
##
- name: Install php-cs-fixer as global composer binary
  become: true
  become_user: vagrant
  command: composer global require friendsofphp/php-cs-fixer:v2.3.2

##
# Add composer bin path to PATH variable
##
- name: add /home/vagrant/.config/composer/vendor/bin/php-cs-fixer to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/home/vagrant/.config/composer/vendor/bin).*?)(["]*)$'
    line="PATH=\1\2:/home/vagrant/.config/composer/vendor/bin\3"

- name: set composer timeout
  lineinfile: >
    dest=/etc/environment
    state=present
    line="COMPOSER_PROCESS_TIMEOUT=900"