---
- hosts: all
  gather_facts: true
  sudo: yes
  vars_files:
    - configuration/TxSolr/main.yml
    - configuration/TxSolr/nginx.yml
    - configuration/TxSolr/php.yml
    - configuration/TxSolr/websites.yml
    - configuration/TxSolr/typo3.yml
  roles:
    - { role: common,    tags: common }
    - { role: geerlingguy.java, tags: java }
    - {
        role: solr,
        tags: solr-7.6,
        solr_port: 8082,
        solr_version: '6.6.2',
        solr_install_path: '/opt/solr_typo3_7_6',
        solr_config_file: '/etc/solr_typo3_7_6.in.sh',
        solr_service_name: 'solr_typo3_7_6',
        solr_home: '/var/solr_typo3_7.6',
        solr_log_file_path: '/var/log/solr.7.6.log',
        solr_cores:
    }
    - {
        role: solr,
        tags: solr-8.7,
        solr_port: 8083,
        solr_version: '6.6.2',
        solr_install_path: '/opt/solr_typo3_8_7',
        solr_config_file: '/etc/solr_typo3_8_7.in.sh',
        solr_service_name: 'solr_typo3_8_7',
        solr_home: '/var/solr_typo3_8.7',
        solr_log_file_path: '/var/log/solr.8.7.log',
        solr_cores:
    }
    - {
        role: solr,
        tags: solr-9.0,
        solr_port: 8084,
        solr_version: '6.6.2',
        solr_install_path: '/opt/solr_typo3_9_0',
        solr_config_file: '/etc/solr_typo3_9_0.in.sh',
        solr_service_name: 'solr_typo3_9_0',
        solr_home: '/var/solr_typo3_9.0',
        solr_log_file_path: '/var/log/solr.9.0.log',
        solr_cores:
    }
    - {
        role: solr,
        tags: solr-dev-master,
        solr_port: 8085,
        solr_version: '7.2.0',
        solr_install_path: '/opt/solr_typo3_dev_master',
        solr_config_file: '/etc/solr_typo3_dev_master.in.sh',
        solr_service_name: 'solr_typo3_dev_master',
        solr_home: '/var/solr_typo3_dev_master',
        solr_log_file_path: '/var/log/solr.dev-master.log',
        solr_cores:
    }
    - { role: geerlingguy.daemonize, tags: daemonize }
    - { role: php-ondrej,   tags: php-ondrej }
    - { role: mariadb,   tags: mariadb }
    - { role: phpcommon, tags: phpcommon }
    - { role: composer-shallow,  tags: composer-shallow }
    - { role: typo3,     tags: typo3 }
    - { role: typo3-solr, tags: typo3-solr }
    - { role: xhprof,    tags: xhprof }
    - { role: memcached, tags: memcached }
    - { role: redis,     tags: redis }
    - { role: nginx,     tags: nginx }
    - { role: nodejs,    tags: nodejs }
